# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sf/ethereum/transform/v1/transforms.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)sf/ethereum/transform/v1/transforms.proto\x12\x18sf.ethereum.transform.v1\"\xd6\x01\n\x0e\x43ombinedFilter\x12\x44\n\x0blog_filters\x18\x01 \x03(\x0b\x32#.sf.ethereum.transform.v1.LogFilterR\nlogFilters\x12I\n\x0c\x63\x61ll_filters\x18\x02 \x03(\x0b\x32&.sf.ethereum.transform.v1.CallToFilterR\x0b\x63\x61llFilters\x12\x33\n\x16send_all_block_headers\x18\x03 \x01(\x08R\x13sendAllBlockHeaders\"V\n\x0eMultiLogFilter\x12\x44\n\x0blog_filters\x18\x01 \x03(\x0b\x32#.sf.ethereum.transform.v1.LogFilterR\nlogFilters\"T\n\tLogFilter\x12\x1c\n\taddresses\x18\x01 \x03(\x0cR\taddresses\x12)\n\x10\x65vent_signatures\x18\x02 \x03(\x0cR\x0f\x65ventSignatures\"^\n\x11MultiCallToFilter\x12I\n\x0c\x63\x61ll_filters\x18\x01 \x03(\x0b\x32&.sf.ethereum.transform.v1.CallToFilterR\x0b\x63\x61llFilters\"L\n\x0c\x43\x61llToFilter\x12\x1c\n\taddresses\x18\x01 \x03(\x0cR\taddresses\x12\x1e\n\nsignatures\x18\x02 \x03(\x0cR\nsignatures\"\x0c\n\nLightBlock\"\x0c\n\nHeaderOnlyBZZXgithub.com/streamingfast/firehose-ethereum/types/pb/sf/ethereum/transform/v1;pbtransformb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sf.ethereum.transform.v1.transforms_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZXgithub.com/streamingfast/firehose-ethereum/types/pb/sf/ethereum/transform/v1;pbtransform'
  _globals['_COMBINEDFILTER']._serialized_start=72
  _globals['_COMBINEDFILTER']._serialized_end=286
  _globals['_MULTILOGFILTER']._serialized_start=288
  _globals['_MULTILOGFILTER']._serialized_end=374
  _globals['_LOGFILTER']._serialized_start=376
  _globals['_LOGFILTER']._serialized_end=460
  _globals['_MULTICALLTOFILTER']._serialized_start=462
  _globals['_MULTICALLTOFILTER']._serialized_end=556
  _globals['_CALLTOFILTER']._serialized_start=558
  _globals['_CALLTOFILTER']._serialized_end=634
  _globals['_LIGHTBLOCK']._serialized_start=636
  _globals['_LIGHTBLOCK']._serialized_end=648
  _globals['_HEADERONLY']._serialized_start=650
  _globals['_HEADERONLY']._serialized_end=662
# @@protoc_insertion_point(module_scope)
