# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sf/ethereum/substreams/v1/rpc.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#sf/ethereum/substreams/v1/rpc.proto\x12\x19sf.ethereum.substreams.v1\"D\n\x08RpcCalls\x12\x38\n\x05\x63\x61lls\x18\x01 \x03(\x0b\x32\".sf.ethereum.substreams.v1.RpcCallR\x05\x63\x61lls\"6\n\x07RpcCall\x12\x17\n\x07to_addr\x18\x01 \x01(\x0cR\x06toAddr\x12\x12\n\x04\x64\x61ta\x18\x02 \x01(\x0cR\x04\x64\x61ta\"T\n\x0cRpcResponses\x12\x44\n\tresponses\x18\x01 \x03(\x0b\x32&.sf.ethereum.substreams.v1.RpcResponseR\tresponses\"7\n\x0bRpcResponse\x12\x10\n\x03raw\x18\x01 \x01(\x0cR\x03raw\x12\x16\n\x06\x66\x61iled\x18\x02 \x01(\x08R\x06\x66\x61iledBWZUgithub.com/streamingfast/firehose-ethereum/types/pb/sf/ethereum/substreams/v1;pbethssb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sf.ethereum.substreams.v1.rpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZUgithub.com/streamingfast/firehose-ethereum/types/pb/sf/ethereum/substreams/v1;pbethss'
  _globals['_RPCCALLS']._serialized_start=66
  _globals['_RPCCALLS']._serialized_end=134
  _globals['_RPCCALL']._serialized_start=136
  _globals['_RPCCALL']._serialized_end=190
  _globals['_RPCRESPONSES']._serialized_start=192
  _globals['_RPCRESPONSES']._serialized_end=276
  _globals['_RPCRESPONSE']._serialized_start=278
  _globals['_RPCRESPONSE']._serialized_end=333
# @@protoc_insertion_point(module_scope)
